//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.ScalableTest.Service.Monitor.DigitalSend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HP.ScalableTest.Service.Monitor.DigitalSend.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER [dbo].[tr_JobLogInsert] ON [dbo].[DssJobLogMaster] FOR INSERT
        ///AS
        ///INSERT INTO STFTransactionLog SELECT JobId, GETDATE() FROM inserted.
        /// </summary>
        internal static string CreateInsertTriggerSql {
            get {
                return ResourceManager.GetString("CreateInsertTriggerSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[STFTransactionLog]&apos;) AND type in (N&apos;U&apos;))
        ///BEGIN
        ///CREATE TABLE [dbo].[STFTransactionLog](
        /// [JobId] [uniqueidentifier] NOT NULL,
        /// [TransactionTime] [datetime] NOT NULL
        ///) ON [PRIMARY]
        ///END.
        /// </summary>
        internal static string CreateTransactionTableSql {
            get {
                return ResourceManager.GetString("CreateTransactionTableSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N&apos;[dbo].[tr_JobLogInsert]&apos;))
        ///DROP TRIGGER [dbo].[tr_JobLogInsert].
        /// </summary>
        internal static string DeleteTriggersSql {
            get {
                return ResourceManager.GetString("DeleteTriggersSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT d.Id, d.JobType, d.CompletionTime, d.XmlJobInfo, a.DeliveredFileName, a.DeliveredFileSize, e.EmailSubject, f.FaxNumber
        ///FROM DSSDeviceJobLog d
        ///LEFT OUTER JOIN DssAttachmentSettings a ON d.Id = a.JobID
        ///LEFT OUTER JOIN DssEmailBasicInformation e ON d.Id = e.JobID
        ///LEFT OUTER JOIN DssFaxJobLogs f ON d.Id = f.JobID
        ///WHERE d.Id IN ({0})
        ///ORDER BY CompletionTime.
        /// </summary>
        internal static string JobLogDeviceSql {
            get {
                return ResourceManager.GetString("JobLogDeviceSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT m.JobID, m.JobType, m.JobCompletionStatus, m.CompletionTime, a.DeliveredFileName, a.DeliveredFileSize, m.FileType, m.ScannedPages, m.DssSoftwareVersion, m.ProcessedBy, m.DeviceModel, e.EmailSubject, f.FaxNumber
        ///FROM DSSJobLogMaster m
        ///LEFT OUTER JOIN DssAttachmentSettings a ON m.JobID = a.JobID
        ///LEFT OUTER JOIN DssEmailBasicInformation e ON m.JobID = e.JobID
        ///LEFT OUTER JOIN DssFaxJobLogs f ON m.JobID = f.JobID
        ///WHERE m.JobID IN ({0})
        ///ORDER BY m.CompletionTime.
        /// </summary>
        internal static string JobLogMasterSql {
            get {
                return ResourceManager.GetString("JobLogMasterSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DeliveredFileName, FaxNumber
        ///FROM (SELECT TOP 200 JobId, CompletionTime FROM DssJobLogMaster ORDER BY CompletionTime DESC) m
        ///INNER JOIN DSSAttachmentSettings a on a.JobID = m.JobID
        ///LEFT OUTER JOIN DSSFaxJobLogs f on f.JobID = m.JobID
        ///ORDER BY CompletionTime DESC.
        /// </summary>
        internal static string RecentSessionSql {
            get {
                return ResourceManager.GetString("RecentSessionSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM STFTransactionLog WITH (ROWLOCK)
        ///WHERE JobID IN ({0}).
        /// </summary>
        internal static string TransactionCleanupSql {
            get {
                return ResourceManager.GetString("TransactionCleanupSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 200 JobId
        ///FROM STFTransactionLog
        ///ORDER BY TransactionTime ASC.
        /// </summary>
        internal static string TransactionRetrieveSql {
            get {
                return ResourceManager.GetString("TransactionRetrieveSql", resourceCulture);
            }
        }
    }
}
