//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.ScalableTest.UI.ScenarioConfiguration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HP.ScalableTest.UI.ScenarioConfiguration.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may assign Active Directory group membership to this worker definition.  At runtime all accounts assigned to run under this worker profile will be added to the defined Active Directory groups.  When the test completes, the assignments will be removed..
        /// </summary>
        internal static string ActiveDirectoryHelp {
            get {
                return ResourceManager.GetString("ActiveDirectoryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will run the full set of activities listed below a specified number of times. One iteration includes all activities in the set.  So, for example, if there are 4 activities listed and the count is 5, all 4 activities will execute 5 times according to the execution order for a total run of 20 activities..
        /// </summary>
        internal static string CountBasedHelp {
            get {
                return ResourceManager.GetString("CountBasedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red80\green80\blue80;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\cf1\f0\fs16\lang9 Note: Pacing is calculated using historical run rates. \ul If you are executing multiple activities\ulnone  it may take a few iterations for the proper pacing to be established.\cf0\par
        ///}
        ///.
        /// </summary>
        internal static string HelpDocument {
            get {
                return ResourceManager.GetString("HelpDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs28\lang9 Scenario Import\par
        ///\b0\fs22 Use this dialog to import a test Scenario from another system or the current system.  First select the import file  below and click &apos;Next&apos; to continue. \par
        ///Because some scenarios rely on external components (devices, queues, drivers, etc.) they may not be the same between systems.  If the Scenar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImportWelcome {
            get {
                return ResourceManager.GetString("ImportWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///Request for increase in Machine Assignments&lt;br /&gt;&lt;br /&gt;
        ///    &lt;b&gt;User:&lt;/b&gt;&amp;nbsp;{USER}&lt;br /&gt;
        ///    &lt;b&gt;Scenario:&lt;/b&gt;&amp;nbsp;{SCENARIO}&lt;br /&gt;
        ///	&lt;br /&gt;
        ///
        ///    &lt;table border=&quot;1&quot; cellpadding=&quot;3&quot; cellspacing=&quot;0&quot; style=&quot;font-family:&apos;Courier New&apos;; font-size:10pt&quot;&gt;
        ///	&lt;thead&gt;
        ///		&lt;tr&gt;
        ///			&lt;th scope=&quot;col&quot;&gt;PlatformId&lt;/th&gt;
        ///			&lt;th scope=&quot;col&quot;&gt;Required&lt;/th&gt;
        ///			&lt;th scope=&quot;col&quot;&gt;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MachineAssignmentIncrease {
            get {
                return ResourceManager.GetString("MachineAssignmentIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load plugin for Activity Type: {0}.
        ///Plugins must exist in the Plugin folder AND in Activity Plugin References to load correctly..
        /// </summary>
        internal static string PluginLoadErrorMessage {
            get {
                return ResourceManager.GetString("PluginLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will run the full set of activities listed below a specified number of times within the defined time period.  One iteration includes all activities in the list and the rate will be adjusted to allow full completion of each activity in the set.  
        ///Note: Pacing is calculated using historical run rates. If you are executing multiple activities it may take a few iterations for the proper pacing to be established..
        /// </summary>
        internal static string RateBasedHelp {
            get {
                return ResourceManager.GetString("RateBasedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Scenario &apos;{0}&apos; was successfully imported. Edit the Scenario and verify that the configuration is as you expected.  Items such as Platform for OfficeWorkers may need to be adjusted..
        /// </summary>
        internal static string ScenarioImportComplete {
            get {
                return ResourceManager.GetString("ScenarioImportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will run the set of activities listed below over a sequence of active/idle periods based on time as defined by the configuration. Click the link to configure the scheduled execution cycle..
        /// </summary>
        internal static string ScheduledHelp {
            get {
                return ResourceManager.GetString("ScheduledHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will run activities for the given duration at given intervals. If the activity cannot be performed at a given time it will be executed at the next given interval time instead of the next available time..
        /// </summary>
        internal static string SetPacedHelp {
            get {
                return ResourceManager.GetString("SetPacedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will continue to run the set of activities listed below according to the execution order over the defined period of time.  When the time frame is met, the execution will stop, which means it is possible that a partial execution of the activity set may occur..
        /// </summary>
        internal static string TimeBasedHelp {
            get {
                return ResourceManager.GetString("TimeBasedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Virtual Worker Account Pools from the Administration menu - Virtual Worker Account Pools.
        /// </summary>
        internal static string UserPoolConfigHelp {
            get {
                return ResourceManager.GetString("UserPoolConfigHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may assign what User Pool this worker&apos;s Domain Accounts will come from.  Change this only if your worker needs to run as a specific user account.  This may be the case when certain solutions must have user accounts predefined and configured on the server and you choose to run the corresponding solution plugin against that server..
        /// </summary>
        internal static string UserPoolHelp {
            get {
                return ResourceManager.GetString("UserPoolHelp", resourceCulture);
            }
        }
    }
}
