//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.ScalableTest.Plugin.ControlPanel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JediResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JediResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HP.ScalableTest.Plugin.ControlPanel.Properties.JediResources", typeof(JediResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell29.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell25.
        /// </summary>
        internal static string Catalan {
            get {
                return ResourceManager.GetString("Catalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell14.
        /// </summary>
        internal static string Cestina {
            get {
                return ResourceManager.GetString("Cestina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell6.
        /// </summary>
        internal static string Dansk {
            get {
                return ResourceManager.GetString("Dansk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell2.
        /// </summary>
        internal static string Deutsch {
            get {
                return ResourceManager.GetString("Deutsch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell0.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell4.
        /// </summary>
        internal static string Espanol {
            get {
                return ResourceManager.GetString("Espanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell1.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell21.
        /// </summary>
        internal static string Hrvatski {
            get {
                return ResourceManager.GetString("Hrvatski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell27.
        /// </summary>
        internal static string Indonesia {
            get {
                return ResourceManager.GetString("Indonesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell3.
        /// </summary>
        internal static string Italiano {
            get {
                return ResourceManager.GetString("Italiano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell16.
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell15.
        /// </summary>
        internal static string Magyar {
            get {
                return ResourceManager.GetString("Magyar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell8.
        /// </summary>
        internal static string Nederlands {
            get {
                return ResourceManager.GetString("Nederlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell7.
        /// </summary>
        internal static string Norsk {
            get {
                return ResourceManager.GetString("Norsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell12.
        /// </summary>
        internal static string Polski {
            get {
                return ResourceManager.GetString("Polski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell10.
        /// </summary>
        internal static string Portugues {
            get {
                return ResourceManager.GetString("Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell22.
        /// </summary>
        internal static string Romana {
            get {
                return ResourceManager.GetString("Romana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell18.
        /// </summary>
        internal static string SimpleChinese {
            get {
                return ResourceManager.GetString("SimpleChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell23.
        /// </summary>
        internal static string Slovancina {
            get {
                return ResourceManager.GetString("Slovancina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell24.
        /// </summary>
        internal static string Slovanscina {
            get {
                return ResourceManager.GetString("Slovanscina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell9.
        /// </summary>
        internal static string Suomi {
            get {
                return ResourceManager.GetString("Suomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell5.
        /// </summary>
        internal static string Svenska {
            get {
                return ResourceManager.GetString("Svenska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell17.
        /// </summary>
        internal static string TraditionalChinese {
            get {
                return ResourceManager.GetString("TraditionalChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell11.
        /// </summary>
        internal static string Turkey {
            get {
                return ResourceManager.GetString("Turkey", resourceCulture);
            }
        }
    }
}
