//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.ScalableTest.Plugin.SoidBerg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HP.ScalableTest.Plugin.SoidBerg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SNMPData&gt;
        ///  &lt;Data&gt;
        ///    &lt;Name&gt;DeviceProductID&lt;/Name&gt;
        ///    &lt;Value&gt;1.3.6.1.2.1.25.3.2.1.4&lt;/Value&gt;
        ///    &lt;IsInteger&gt;1&lt;/IsInteger&gt;
        ///    &lt;Command&gt;GetNext&lt;/Command&gt;
        ///    &lt;Comments&gt;Gets the product ID for the device (when GetNext is called).&lt;/Comments&gt;
        ///  &lt;/Data&gt;
        ///  &lt;Data&gt;
        ///    &lt;Name&gt;DeviceStatus&lt;/Name&gt;
        ///    &lt;Value&gt;1.3.6.1.2.1.25.3.2.1.5.1&lt;/Value&gt;
        ///    &lt;IsInteger&gt;0&lt;/IsInteger&gt;
        ///    &lt;Command&gt;Get&lt;/Command&gt;
        ///    &lt;Comments&gt;Gets the device status.&lt;/Comments&gt;
        ///  &lt;/Data&gt;
        ///  &lt;Data&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SNMPData {
            get {
                return ResourceManager.GetString("SNMPData", resourceCulture);
            }
        }
    }
}
