//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.ScalableTest.Plugin.CertificateInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HP.ScalableTest.Plugin.CertificateInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dot1x_auth_eap_username={0}&amp;dot1x_auth_eap_passwd=&amp;dot1x_auth_eap_passwd_conf=&amp;dot1x_auth_eap_serverid=&amp;dot1x_auth_eap_encrstr=EAP_ENCRSTR_LOW&amp;dot1xcfg_cacert=Configure...&amp;AuthState=BLOCK&amp;dot1x_auth_reauth=on&amp;Hide=26909.
        /// </summary>
        internal static string ConfigRequestJediDelete {
            get {
                return ResourceManager.GetString("ConfigRequestJediDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish=Finish&amp;Hide=.
        /// </summary>
        internal static string FinishData {
            get {
                return ResourceManager.GetString("FinishData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/jpeg, application/x-ms-application, image/gif, application/xaml+xml, image/pjpeg, application/x-ms-xbap, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*.
        /// </summary>
        internal static string GetRequestAccept {
            get {
                return ResourceManager.GetString("GetRequestAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to certoptions=DELCACERT&amp;Next=Next+%3E&amp;year=&amp;month=&amp;day=&amp;hour=&amp;minute=&amp;EndDate=2019-05-02+11%3A12+UTC&amp;StartDate=2014-05-02+11%3A12+UTC&amp;Hide=.
        /// </summary>
        internal static string OptionRequestJediDelete {
            get {
                return ResourceManager.GetString("OptionRequestJediDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to certoptions=INSTALLCACERT&amp;Next=Next+%3E&amp;year=&amp;month=&amp;day=&amp;hour=&amp;minute=&amp;EndDate=2019-05-05+09%3A04+UTC&amp;StartDate=2014-05-05+09%3A04+UTC&amp;Hide=.
        /// </summary>
        internal static string OptionRequestJediInstall {
            get {
                return ResourceManager.GetString("OptionRequestJediInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}set_config_networkCAResult.html?tab=Networking&amp;amp;menu=NetCerts.
        /// </summary>
        internal static string UploadStatus {
            get {
                return ResourceManager.GetString("UploadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}set_config_networkCAResultFail.html?tab=Networking&amp;amp;menu=NetCerts.
        /// </summary>
        internal static string UploadStatusPfx {
            get {
                return ResourceManager.GetString("UploadStatusPfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security/CACertificate/Info.
        /// </summary>
        internal static string URLInkVerify {
            get {
                return ResourceManager.GetString("URLInkVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security/CACertificate/Upload.
        /// </summary>
        internal static string URLInstallInkCer {
            get {
                return ResourceManager.GetString("URLInstallInkCer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security/CACertificate/Upload?fixed_response=true.
        /// </summary>
        internal static string URLInstallInkPfx {
            get {
                return ResourceManager.GetString("URLInstallInkPfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hp/device/CertificateCA.pem.
        /// </summary>
        internal static string URLInstallPhoenix {
            get {
                return ResourceManager.GetString("URLInstallPhoenix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to websecurity/cert_results.html/config.
        /// </summary>
        internal static string URLJediClose {
            get {
                return ResourceManager.GetString("URLJediClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to websecurity/cert_option.html/config.
        /// </summary>
        internal static string URLJediCookie {
            get {
                return ResourceManager.GetString("URLJediCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dot1x_config.htm/config.
        /// </summary>
        internal static string URLJediDeleteWizard {
            get {
                return ResourceManager.GetString("URLJediDeleteWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error_back.htm/config.
        /// </summary>
        internal static string URLJediError {
            get {
                return ResourceManager.GetString("URLJediError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to websecurity/cert_finish.html/config.
        /// </summary>
        internal static string URLJediFinish {
            get {
                return ResourceManager.GetString("URLJediFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hp/device/DeviceStatus/Index.
        /// </summary>
        internal static string URLJediHome {
            get {
                return ResourceManager.GetString("URLJediHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to websecurity/cert_install.html/config.
        /// </summary>
        internal static string URLJediUpload {
            get {
                return ResourceManager.GetString("URLJediUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to websecurity/cert_status1.html.
        /// </summary>
        internal static string URLJediVerify {
            get {
                return ResourceManager.GetString("URLJediVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to websecurity/cert_status1.html/config.
        /// </summary>
        internal static string URLJediWizard {
            get {
                return ResourceManager.GetString("URLJediWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hp/device/set_config_networkCADel.html/config.
        /// </summary>
        internal static string URLPhoenixDelete {
            get {
                return ResourceManager.GetString("URLPhoenixDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hp/device/set_config_networkCerts.html?tab=Networking&amp;menu=NetCerts.
        /// </summary>
        internal static string URLPhoenixVerify {
            get {
                return ResourceManager.GetString("URLPhoenixVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-ms-application, image/jpeg, application/xaml+xml, image/gif, image/pjpeg, application/x-ms-xbap, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*.
        /// </summary>
        internal static string WebRequestAccept {
            get {
                return ResourceManager.GetString("WebRequestAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAconfigure=Configure...&amp;Hide=12792.
        /// </summary>
        internal static string WizardRequest {
            get {
                return ResourceManager.GetString("WizardRequest", resourceCulture);
            }
        }
    }
}
