//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.ScalableTest.Plugin.HpecInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HP.ScalableTest.Plugin.HpecInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DeviceList xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt; DL#752462&lt;/Name&gt;
        ///  &lt;Devices&gt;
        ///    &lt;Device guid=&quot;0e737853-c1d0-4900-a3d3-593a305c5c1d&quot; deviceId=&quot;HP LaserJet MFP E72535#CN48JDR00S&quot; ipAddress=&quot;15.85.92.217&quot; httpPort=&quot;80&quot; httpsPort=&quot;443&quot; snmpPort=&quot;161&quot;&gt;
        ///      &lt;Username&gt;admin&lt;/Username&gt;
        ///      &lt;Password&gt;--Boundary93504AC0-71EE-49dd-AEB3-D3EF6D251BEA------iomnFARkiXgHO9laozEA7Q==&lt;/Password&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeviceList {
            get {
                return ResourceManager.GetString("DeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TaskList xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;InstallEC&lt;/Name&gt;
        ///  &lt;Tasks&gt;
        ///    &lt;Task name=&quot;Check if a Bundle is installed&quot; assembly=&quot;Hp.NSE.FDT&quot; classname=&quot;Hp.NSE.FDT.JediTasks.CheckIfBundleIsInstalled&quot;&gt;
        ///      &lt;ActionIfError&gt;ABORT&lt;/ActionIfError&gt;
        ///      &lt;ExecutionFilter xsi:type=&quot;CustomExpression&quot;&gt;
        ///        &lt;Name&gt;[EMPTY]&lt;/Name&gt;
        ///        &lt;Type&gt;CustomExpression&lt;/Type&gt;
        ///        &lt;Operands /&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstallHpec {
            get {
                return ResourceManager.GetString("InstallHpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TaskList xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;RemoveECWorkflow&lt;/Name&gt;
        ///  &lt;Tasks&gt;
        ///    &lt;Task name=&quot;Check if a Bundle is installed&quot; assembly=&quot;Hp.NSE.FDT&quot; classname=&quot;Hp.NSE.FDT.JediTasks.CheckIfBundleIsInstalled&quot;&gt;
        ///      &lt;ActionIfError&gt;ABORT&lt;/ActionIfError&gt;
        ///      &lt;ExecutionFilter xsi:type=&quot;CustomExpression&quot;&gt;
        ///        &lt;Name&gt;[EMPTY]&lt;/Name&gt;
        ///        &lt;Type&gt;CustomExpression&lt;/Type&gt;
        ///        &lt;Operands /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RemoveWorkFlow {
            get {
                return ResourceManager.GetString("RemoveWorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TaskList xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;UninstallEC&lt;/Name&gt;
        ///  &lt;Tasks&gt;
        ///    &lt;Task name=&quot;Check if a Bundle is installed&quot; assembly=&quot;Hp.NSE.FDT&quot; classname=&quot;Hp.NSE.FDT.JediTasks.CheckIfBundleIsInstalled&quot;&gt;
        ///      &lt;ActionIfError&gt;ABORT&lt;/ActionIfError&gt;
        ///      &lt;ExecutionFilter xsi:type=&quot;CustomExpression&quot;&gt;
        ///        &lt;Name&gt;[EMPTY]&lt;/Name&gt;
        ///        &lt;Type&gt;CustomExpression&lt;/Type&gt;
        ///        &lt;Operands /&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UninstallHpec {
            get {
                return ResourceManager.GetString("UninstallHpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TaskList xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;UploadECWorkflow&lt;/Name&gt;
        ///  &lt;Tasks&gt;
        ///    &lt;Task name=&quot;Check if a Bundle is installed&quot; assembly=&quot;Hp.NSE.FDT&quot; classname=&quot;Hp.NSE.FDT.JediTasks.CheckIfBundleIsInstalled&quot;&gt;
        ///      &lt;ActionIfError&gt;ABORT&lt;/ActionIfError&gt;
        ///      &lt;ExecutionFilter xsi:type=&quot;CustomExpression&quot;&gt;
        ///        &lt;Name&gt;[EMPTY]&lt;/Name&gt;
        ///        &lt;Type&gt;CustomExpression&lt;/Type&gt;
        ///        &lt;Operands /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UploadWorkFlow {
            get {
                return ResourceManager.GetString("UploadWorkFlow", resourceCulture);
            }
        }
    }
}
