USE [master]
GO
CREATE DATABASE [EPrintMonitor]
GO
ALTER DATABASE [EPrintMonitor] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE EPrintMonitor MODIFY FILE
( NAME = N'EPrintMonitor', SIZE = 4096KB , MAXSIZE = 50MB, FILEGROWTH = 1024KB )
GO
ALTER DATABASE EPrintMonitor MODIFY FILE
( NAME = N'EPrintMonitor_log', SIZE = 1024KB , MAXSIZE = 50MB , FILEGROWTH = 10% )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EPrintMonitor].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EPrintMonitor] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EPrintMonitor] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EPrintMonitor] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EPrintMonitor] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EPrintMonitor] SET ARITHABORT OFF 
GO
ALTER DATABASE [EPrintMonitor] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [EPrintMonitor] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [EPrintMonitor] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [EPrintMonitor] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EPrintMonitor] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EPrintMonitor] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EPrintMonitor] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EPrintMonitor] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EPrintMonitor] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EPrintMonitor] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EPrintMonitor] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EPrintMonitor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EPrintMonitor] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EPrintMonitor] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EPrintMonitor] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EPrintMonitor] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EPrintMonitor] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EPrintMonitor] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EPrintMonitor] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [EPrintMonitor] SET  MULTI_USER 
GO
ALTER DATABASE [EPrintMonitor] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EPrintMonitor] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EPrintMonitor] SET  READ_WRITE 
GO
USE [EPrintMonitor]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pending](
	[JobId] [int] NOT NULL,
	[IsInsert] [bit] NOT NULL,
 CONSTRAINT [PK_Transaction] PRIMARY KEY CLUSTERED 
(
	[JobId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS OFF
GO
ALTER AUTHORIZATION ON DATABASE::[EPrintMonitor] to cloudprint;