//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     J2: Template .\Templates
//         using modules ['Xml2CS']
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.ScalableTest.Plugin.TwainDriverConfiguration.UIMaps
{
    using TopCat.TestApi.GUIAutomation.Controls;
    using TopCat.TestApi.GUIAutomation.Enums;

    /// <summary>
    /// Application which exercises the TopCat Coded C# test API.
    /// </summary>
    public class SaveOperations
    {
        /// <summary>
        /// Backing field for HPScanHPLaserJeWindow property
        /// </summary>
        private Window fHPScanHPLaserJeWindow;

        /// <summary>
        /// Backing field for HPScanStatic106Text property
        /// </summary>
        private Text fHPScanStatic106Text;

        /// <summary>
        /// Backing field for HPLaserJetMFPM5Text property
        /// </summary>
        private Text fHPLaserJetMFPM5Text;

        /// <summary>
        /// Backing field for A11Static1066Dup0I0XText property
        /// </summary>
        private Text fA11Static1066Dup0I0XText;

        /// <summary>
        /// Backing field for A11Static1066Dup1I1XText property
        /// </summary>
        private Text fA11Static1066Dup1I1XText;

        /// <summary>
        /// Backing field for DetailedAdjustmText property
        /// </summary>
        private Text fDetailedAdjustmText;

        /// <summary>
        /// Backing field for SaveButton1006Button property
        /// </summary>
        private Button fSaveButton1006Button;

        /// <summary>
        /// Backing field for ExitButton1007Button property
        /// </summary>
        private Button fExitButton1007Button;

        /// <summary>
        /// Backing field for BackButton1005Button property
        /// </summary>
        private Button fBackButton1005Button;

        /// <summary>
        /// Backing field for Button1000Button property
        /// </summary>
        private Button fButton1000Button;

        /// <summary>
        /// Backing field for Button210Button property
        /// </summary>
        private Button fButton210Button;

        /// <summary>
        /// Backing field for Button1023Button property
        /// </summary>
        private Button fButton1023Button;

        /// <summary>
        /// Backing field for A32770Dup0I0XPane property
        /// </summary>
        private Pane fA32770Dup0I0XPane;

        /// <summary>
        /// Backing field for ImageButton1017Button property
        /// </summary>
        private Button fImageButton1017Button;

        /// <summary>
        /// Backing field for DocumentButton1Button property
        /// </summary>
        private Button fDocumentButton1Button;

        /// <summary>
        /// Backing field for DestinationButtButton property
        /// </summary>
        private Button fDestinationButtButton;

        /// <summary>
        /// Backing field for ManageImagesButButton property
        /// </summary>
        private Button fManageImagesButButton;

        /// <summary>
        /// Backing field for A32770Dup1Pane property
        /// </summary>
        private Pane fA32770Dup1Pane;

        /// <summary>
        /// Backing field for Button1078Button property
        /// </summary>
        private Button fButton1078Button;

        /// <summary>
        /// Backing field for FileTypeStaticText property
        /// </summary>
        private Text fFileTypeStaticText;

        /// <summary>
        /// Backing field for FileTypeButton1Button property
        /// </summary>
        private Button fFileTypeButton1Button;

        /// <summary>
        /// Backing field for FileNameStaticText property
        /// </summary>
        private Text fFileNameStaticText;

        /// <summary>
        /// Backing field for FileNameComboBoComboBox property
        /// </summary>
        private ComboBox fFileNameComboBoComboBox;

        /// <summary>
        /// Backing field for FileNameComboLBList property
        /// </summary>
        private List fFileNameComboLBList;

        /// <summary>
        /// Backing field for LocalorNetworkfListItem property
        /// </summary>
        private ListItem fLocalorNetworkfListItem;

        /// <summary>
        /// Backing field for DropDownButtonDButton property
        /// </summary>
        private Button fDropDownButtonDButton;

        /// <summary>
        /// Backing field for SendToStaticText property
        /// </summary>
        private Text fSendToStaticText;

        /// <summary>
        /// Backing field for SendToEdit1159Edit property
        /// </summary>
        private Edit fSendToEdit1159Edit;

        /// <summary>
        /// Backing field for BrowseButton116Button property
        /// </summary>
        private Button fBrowseButton116Button;

        /// <summary>
        /// Backing field for ShowSaveAsdialoButton property
        /// </summary>
        private Button fShowSaveAsdialoButton;

        /// <summary>
        /// Backing field for ShowSaveAsdialoCheckBox property
        /// </summary>
        private CheckBox fShowSaveAsdialoCheckBox;

        /// <summary>
        /// Backing field for OpenthefileButtButton property
        /// </summary>
        private Button fOpenthefileButtButton;

        /// <summary>
        /// Backing field for LaunchWindowsExButton property
        /// </summary>
        private Button fLaunchWindowsExButton;

        /// <summary>
        /// Backing field for DoNothingButtonButton property
        /// </summary>
        private Button fDoNothingButtonButton;

        /// <summary>
        /// Backing field for DoNothingButtonRadioButton property
        /// </summary>
        private RadioButton fDoNothingButtonRadioButton;

        /// <summary>
        /// Backing field for AftersavingthefText property
        /// </summary>
        private Text fAftersavingthefText;

        /// <summary>
        /// Backing field for A32770Dup2I1XPane property
        /// </summary>
        private Pane fA32770Dup2I1XPane;

        /// <summary>
        /// Backing field for Button2132Button property
        /// </summary>
        private Button fButton2132Button;

        /// <summary>
        /// Backing field for Button1165Button property
        /// </summary>
        private Button fButton1165Button;

        /// <summary>
        /// Backing field for Button288Button property
        /// </summary>
        private Button fButton288Button;

        /// <summary>
        /// Backing field for ScanEdit1869Edit property
        /// </summary>
        private Edit fScanEdit1869Edit;

        /// <summary>
        /// Backing field for OKButton1Button property
        /// </summary>
        private Button fOKButton1Button;

        /// <summary>
        /// Backing field for HPScanHPLaserJePane property
        /// </summary>
        private Pane fHPScanHPLaserJePane;

        /// <summary>
        /// Backing field for YesButton1ButtonReplace property
        /// </summary>
        private Button fYesButton1ButtonReplace;

        /// <summary>
        /// Backing field for NoButton1845Button property
        /// </summary>
        private Button fNoButton1845Button;

        /// <summary>
        /// Backing field for SavealocalcopyBButton property
        /// </summary>
        private Button fSavealocalcopyBButton;

        /// <summary>
        /// Backing field for SavealocalcopyBCheckBox property
        /// </summary>
        private CheckBox fSavealocalcopyBCheckBox;

        /// <summary>
        /// Model Name property
        /// </summary>
        private string _modelName;

        /// <summary>
        /// Initializes a new instance of the <see cref="SaveOperations"/> class.
        /// </summary>
        /// <param name="framework">
        /// The framework.
        /// </param>
        public SaveOperations(UIAFramework framework)
        {
            Desktop = new Desktop(framework);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SaveOperations"/> class using the default UIAFramework.
        /// </summary>
        public SaveOperations()
        {
            Desktop = new Desktop();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SaveOperations"/> class.
        /// </summary>
        /// <param name="modelName">
        /// The framework.
        /// </param>
        public SaveOperations(string modelName)
        {
            _modelName = modelName;
            Desktop = new Desktop(UIAFramework.ManagedUIA);
        }


        /// <summary>
        /// Gets Reference to desktop
        /// </summary>
        public Desktop Desktop { get; private set; }

        /// <summary>
        /// Gets Reference to HPScanHPLaserJeWindow
        /// </summary>
        public Window HPScanHPLaserJeWindow
        {
            get
            {
                if (null == fHPScanHPLaserJeWindow)
                {
                    fHPScanHPLaserJeWindow = new Window("HPScanHPLaserJeWindow", Desktop);
                    fHPScanHPLaserJeWindow.UIMap.Scope = UIASeachScope.Children;
                    fHPScanHPLaserJeWindow.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"#32770");
                    fHPScanHPLaserJeWindow.UIMap.SearchProperties.Add(UIASearchProperty.Name, $@"HP Scan - {_modelName}");
                }

                return fHPScanHPLaserJeWindow;
            }
        }

        /// <summary>
        /// Gets Reference to HPScanHPLaserJePane
        /// </summary>
        public Pane HPScanHPLaserJePane
        {
            get
            {
                if (null == fHPScanHPLaserJePane)
                {
                    fHPScanHPLaserJePane = new Pane("HPScanHPLaserJePane", HPScanHPLaserJeWindow);
                    fHPScanHPLaserJePane.UIMap.Scope = UIASeachScope.Children;
                    fHPScanHPLaserJePane.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"#32770");
                    fHPScanHPLaserJePane.UIMap.SearchProperties.Add(UIASearchProperty.Name, $@"HP Scan - {_modelName}");
                }

                return fHPScanHPLaserJePane;
            }
        }

        /// <summary>
        /// Gets Reference to HPScanStatic106Text
        /// </summary>
        public Text HPScanStatic106Text
        {
            get
            {
                if (null == fHPScanStatic106Text)
                {
                    fHPScanStatic106Text = new Text("HPScanStatic106Text", HPScanHPLaserJeWindow);
                    fHPScanStatic106Text.UIMap.Scope = UIASeachScope.Children;
                    fHPScanStatic106Text.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1066");
                    fHPScanStatic106Text.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Static");
                    fHPScanStatic106Text.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"HP Scan");
                }

                return fHPScanStatic106Text;
            }
        }

        /// <summary>
        /// Gets Reference to HPLaserJetMFPM5Text
        /// </summary>
        public Text HPLaserJetMFPM5Text
        {
            get
            {
                if (null == fHPLaserJetMFPM5Text)
                {
                    fHPLaserJetMFPM5Text = new Text("HPLaserJetMFPM5Text", HPScanHPLaserJeWindow);
                    fHPLaserJetMFPM5Text.UIMap.Scope = UIASeachScope.Children;
                    fHPLaserJetMFPM5Text.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1066");
                    fHPLaserJetMFPM5Text.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Static");
                    fHPLaserJetMFPM5Text.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"HP LaserJet MFP M527");
                }

                return fHPLaserJetMFPM5Text;
            }
        }

        /// <summary>
        /// Gets Reference to A11Static1066Dup0I0XText
        /// </summary>
        public Text A11Static1066Dup0I0XText
        {
            get
            {
                if (null == fA11Static1066Dup0I0XText)
                {
                    fA11Static1066Dup0I0XText = new Text("A11Static1066Dup0I0XText", HPScanHPLaserJeWindow);
                    fA11Static1066Dup0I0XText.UIMap.Scope = UIASeachScope.Children;
                    fA11Static1066Dup0I0XText.UIMap.Index = 0;
                    fA11Static1066Dup0I0XText.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1066");
                    fA11Static1066Dup0I0XText.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Static");
                    fA11Static1066Dup0I0XText.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"1/1");
                }

                return fA11Static1066Dup0I0XText;
            }
        }

        /// <summary>
        /// Gets Reference to A11Static1066Dup1I1XText
        /// </summary>
        public Text A11Static1066Dup1I1XText
        {
            get
            {
                if (null == fA11Static1066Dup1I1XText)
                {
                    fA11Static1066Dup1I1XText = new Text("A11Static1066Dup1I1XText", HPScanHPLaserJeWindow);
                    fA11Static1066Dup1I1XText.UIMap.Scope = UIASeachScope.Children;
                    fA11Static1066Dup1I1XText.UIMap.Index = 1;
                    fA11Static1066Dup1I1XText.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1066");
                    fA11Static1066Dup1I1XText.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Static");
                    fA11Static1066Dup1I1XText.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"1/1");
                }

                return fA11Static1066Dup1I1XText;
            }
        }

        /// <summary>
        /// Gets Reference to DetailedAdjustmText
        /// </summary>
        public Text DetailedAdjustmText
        {
            get
            {
                if (null == fDetailedAdjustmText)
                {
                    fDetailedAdjustmText = new Text("DetailedAdjustmText", HPScanHPLaserJeWindow);
                    fDetailedAdjustmText.UIMap.Scope = UIASeachScope.Children;
                    fDetailedAdjustmText.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1066");
                    fDetailedAdjustmText.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Static");
                    fDetailedAdjustmText.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Detailed Adjustments");
                }

                return fDetailedAdjustmText;
            }
        }

        /// <summary>
        /// Gets Reference to SaveButton1006Button
        /// </summary>
        public Button SaveButton1006Button
        {
            get
            {
                if (null == fSaveButton1006Button)
                {
                    fSaveButton1006Button = new Button("SaveButton1006Button", HPScanHPLaserJeWindow);
                    fSaveButton1006Button.UIMap.Scope = UIASeachScope.Children;
                    fSaveButton1006Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1006");
                    fSaveButton1006Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                    fSaveButton1006Button.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Save");
                }

                return fSaveButton1006Button;
            }
        }

        /// <summary>
        /// Gets Reference to ExitButton1007Button
        /// </summary>
        public Button ExitButton1007Button
        {
            get
            {
                if (null == fExitButton1007Button)
                {
                    fExitButton1007Button = new Button("ExitButton1007Button", HPScanHPLaserJeWindow);
                    fExitButton1007Button.UIMap.Scope = UIASeachScope.Children;
                    fExitButton1007Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1007");
                    fExitButton1007Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                    fExitButton1007Button.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Exit");
                }

                return fExitButton1007Button;
            }
        }

        /// <summary>
        /// Gets Reference to BackButton1005Button
        /// </summary>
        public Button BackButton1005Button
        {
            get
            {
                if (null == fBackButton1005Button)
                {
                    fBackButton1005Button = new Button("BackButton1005Button", HPScanHPLaserJeWindow);
                    fBackButton1005Button.UIMap.Scope = UIASeachScope.Children;
                    fBackButton1005Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1005");
                    fBackButton1005Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                    fBackButton1005Button.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Back");
                }

                return fBackButton1005Button;
            }
        }

        /// <summary>
        /// Gets Reference to Button1000Button
        /// </summary>
        public Button Button1000Button
        {
            get
            {
                if (null == fButton1000Button)
                {
                    fButton1000Button = new Button("Button1000Button", HPScanHPLaserJeWindow);
                    fButton1000Button.UIMap.Scope = UIASeachScope.Children;
                    fButton1000Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1000");
                    fButton1000Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                }

                return fButton1000Button;
            }
        }

        /// <summary>
        /// Gets Reference to Button210Button
        /// </summary>
        public Button Button210Button
        {
            get
            {
                if (null == fButton210Button)
                {
                    fButton210Button = new Button("Button210Button", HPScanHPLaserJeWindow);
                    fButton210Button.UIMap.Scope = UIASeachScope.Children;
                    fButton210Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"210");
                    fButton210Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                }

                return fButton210Button;
            }
        }

        /// <summary>
        /// Gets Reference to Button1023Button
        /// </summary>
        public Button Button1023Button
        {
            get
            {
                if (null == fButton1023Button)
                {
                    fButton1023Button = new Button("Button1023Button", HPScanHPLaserJeWindow);
                    fButton1023Button.UIMap.Scope = UIASeachScope.Children;
                    fButton1023Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1023");
                    fButton1023Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                }

                return fButton1023Button;
            }
        }

        /// <summary>
        /// Gets Reference to A32770Dup0I0XPane
        /// </summary>
        public Pane A32770Dup0I0XPane
        {
            get
            {
                if (null == fA32770Dup0I0XPane)
                {
                    fA32770Dup0I0XPane = new Pane("A32770Dup0I0XPane", HPScanHPLaserJeWindow);
                    fA32770Dup0I0XPane.UIMap.Scope = UIASeachScope.Children;
                    fA32770Dup0I0XPane.UIMap.Index = 0;
                    fA32770Dup0I0XPane.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"#32770");
                }

                return fA32770Dup0I0XPane;
            }
        }

        /// <summary>
        /// Gets Reference to ImageButton1017Button
        /// </summary>
        public Button ImageButton1017Button
        {
            get
            {
                if (null == fImageButton1017Button)
                {
                    fImageButton1017Button = new Button("ImageButton1017Button", A32770Dup0I0XPane);
                    fImageButton1017Button.UIMap.Scope = UIASeachScope.Children;
                    fImageButton1017Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1017");
                    fImageButton1017Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                    fImageButton1017Button.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Image");
                }

                return fImageButton1017Button;
            }
        }

        /// <summary>
        /// Gets Reference to DocumentButton1Button
        /// </summary>
        public Button DocumentButton1Button
        {
            get
            {
                if (null == fDocumentButton1Button)
                {
                    fDocumentButton1Button = new Button("DocumentButton1Button", A32770Dup0I0XPane);
                    fDocumentButton1Button.UIMap.Scope = UIASeachScope.Children;
                    fDocumentButton1Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1018");
                    fDocumentButton1Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                    fDocumentButton1Button.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Document");
                }

                return fDocumentButton1Button;
            }
        }

        /// <summary>
        /// Gets Reference to DestinationButtButton
        /// </summary>
        public Button DestinationButtButton
        {
            get
            {
                if (null == fDestinationButtButton)
                {
                    fDestinationButtButton = new Button("DestinationButtButton", A32770Dup0I0XPane);
                    fDestinationButtButton.UIMap.Scope = UIASeachScope.Children;
                    fDestinationButtButton.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1020");
                    fDestinationButtButton.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");          
                }

                return fDestinationButtButton;
            }
        }

        /// <summary>
        /// Gets Reference to ManageImagesButButton
        /// </summary>
        public Button ManageImagesButButton
        {
            get
            {
                if (null == fManageImagesButButton)
                {
                    fManageImagesButButton = new Button("ManageImagesButButton", A32770Dup0I0XPane);
                    fManageImagesButButton.UIMap.Scope = UIASeachScope.Children;
                    fManageImagesButButton.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1173");
                    fManageImagesButButton.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                    fManageImagesButButton.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Manage Images");
                }

                return fManageImagesButButton;
            }
        }

        /// <summary>
        /// Gets Reference to A32770Dup1Pane
        /// </summary>
        public Pane A32770Dup1Pane
        {
            get
            {
                if (null == fA32770Dup1Pane)
                {
                    fA32770Dup1Pane = new Pane("A32770Dup1Pane", A32770Dup0I0XPane);
                    fA32770Dup1Pane.UIMap.Scope = UIASeachScope.Children;
                    fA32770Dup1Pane.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"#32770");
                }

                return fA32770Dup1Pane;
            }
        }

        /// <summary>
        /// Gets Reference to Button1078Button
        /// </summary>
        public Button Button1078Button
        {
            get
            {
                if (null == fButton1078Button)
                {
                    fButton1078Button = new Button("Button1078Button", A32770Dup1Pane);
                    fButton1078Button.UIMap.Scope = UIASeachScope.Children;
                    fButton1078Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1078");
                    fButton1078Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                }

                return fButton1078Button;
            }
        }

        /// <summary>
        /// Gets Reference to FileTypeStaticText
        /// </summary>
        public Text FileTypeStaticText
        {
            get
            {
                if (null == fFileTypeStaticText)
                {
                    fFileTypeStaticText = new Text("FileTypeStaticText", A32770Dup1Pane);
                    fFileTypeStaticText.UIMap.Scope = UIASeachScope.Children;
                    fFileTypeStaticText.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Static");
                    fFileTypeStaticText.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"File Type");
                }

                return fFileTypeStaticText;
            }
        }

        /// <summary>
        /// Gets Reference to FileTypeButton1Button
        /// </summary>
        public Button FileTypeButton1Button
        {
            get
            {
                if (null == fFileTypeButton1Button)
                {
                    fFileTypeButton1Button = new Button("FileTypeButton1Button", A32770Dup1Pane);
                    fFileTypeButton1Button.UIMap.Scope = UIASeachScope.Children;
                    fFileTypeButton1Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1866");
                    fFileTypeButton1Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");          
                }

                return fFileTypeButton1Button;
            }
        }

        /// <summary>
        /// Gets Reference to FileNameStaticText
        /// </summary>
        public Text FileNameStaticText
        {
            get
            {
                if (null == fFileNameStaticText)
                {
                    fFileNameStaticText = new Text("FileNameStaticText", A32770Dup1Pane);
                    fFileNameStaticText.UIMap.Scope = UIASeachScope.Children;
                    fFileNameStaticText.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Static");
                    fFileNameStaticText.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"File Name");
                }

                return fFileNameStaticText;
            }
        }

        /// <summary>
        /// Gets Reference to FileNameComboBoComboBox
        /// </summary>
        public ComboBox FileNameComboBoComboBox
        {
            get
            {
                if (null == fFileNameComboBoComboBox)
                {
                    fFileNameComboBoComboBox = new ComboBox("FileNameComboBoComboBox", A32770Dup1Pane);
                    fFileNameComboBoComboBox.UIMap.Scope = UIASeachScope.Children;
                    fFileNameComboBoComboBox.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1118");
                    fFileNameComboBoComboBox.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"ComboBox");
                }

                return fFileNameComboBoComboBox;
            }
        }

        /// <summary>
        /// Gets Reference to FileNameComboLBList
        /// </summary>
        public List FileNameComboLBList
        {
            get
            {
                if (null == fFileNameComboLBList)
                {
                    fFileNameComboLBList = new List("FileNameComboLBList", FileNameComboBoComboBox);
                    fFileNameComboLBList.UIMap.Scope = UIASeachScope.Children;
                    fFileNameComboLBList.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"ListBox");
                    fFileNameComboLBList.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"ComboLBox");
                    fFileNameComboLBList.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"File Name");
                }

                return fFileNameComboLBList;
            }
        }

        /// <summary>
        /// Gets Reference to LocalorNetworkfListItem
        /// </summary>
        public ListItem LocalorNetworkfListItem
        {
            get
            {
                if (null == fLocalorNetworkfListItem)
                {
                    fLocalorNetworkfListItem = new ListItem("LocalorNetworkfListItem", FileNameComboLBList);
                    fLocalorNetworkfListItem.UIMap.Scope = UIASeachScope.Children;
                    fLocalorNetworkfListItem.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Local or Network folder");
                }

                return fLocalorNetworkfListItem;
            }
        }

        /// <summary>
        /// Gets Reference to DropDownButtonDButton
        /// </summary>
        public Button DropDownButtonDButton
        {
            get
            {
                if (null == fDropDownButtonDButton)
                {
                    fDropDownButtonDButton = new Button("DropDownButtonDButton", FileNameComboBoComboBox);
                    fDropDownButtonDButton.UIMap.Scope = UIASeachScope.Children;
                    fDropDownButtonDButton.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"DropDown");
                    fDropDownButtonDButton.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Drop Down Button");
                }

                return fDropDownButtonDButton;
            }
        }

        /// <summary>
        /// Gets Reference to SendToStaticText
        /// </summary>
        public Text SendToStaticText
        {
            get
            {
                if (null == fSendToStaticText)
                {
                    fSendToStaticText = new Text("SendToStaticText", A32770Dup1Pane);
                    fSendToStaticText.UIMap.Scope = UIASeachScope.Children;
                    fSendToStaticText.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Static");
                    fSendToStaticText.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Send To");
                }

                return fSendToStaticText;
            }
        }

        /// <summary>
        /// Gets Reference to SendToEdit1159Edit
        /// </summary>
        public Edit SendToEdit1159Edit
        {
            get
            {
                if (null == fSendToEdit1159Edit)
                {
                    fSendToEdit1159Edit = new Edit("SendToEdit1159Edit", A32770Dup1Pane);
                    fSendToEdit1159Edit.UIMap.Scope = UIASeachScope.Children;
                    fSendToEdit1159Edit.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1159");
                    fSendToEdit1159Edit.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Edit");            
                }

                return fSendToEdit1159Edit;
            }
        }

        /// <summary>
        /// Gets Reference to BrowseButton116Button
        /// </summary>
        public Button BrowseButton116Button
        {
            get
            {
                if (null == fBrowseButton116Button)
                {
                    fBrowseButton116Button = new Button("BrowseButton116Button", A32770Dup1Pane);
                    fBrowseButton116Button.UIMap.Scope = UIASeachScope.Children;
                    fBrowseButton116Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1168");
                    fBrowseButton116Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                    fBrowseButton116Button.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Browse");
                }

                return fBrowseButton116Button;
            }
        }

        /// <summary>
        /// Gets Reference to ShowSaveAsdialoButton
        /// </summary>
        public Button ShowSaveAsdialoButton
        {
            get
            {
                if (null == fShowSaveAsdialoButton)
                {
                    fShowSaveAsdialoButton = new Button("ShowSaveAsdialoButton", A32770Dup1Pane);
                    fShowSaveAsdialoButton.UIMap.Scope = UIASeachScope.Children;
                    fShowSaveAsdialoButton.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1161");
                    fShowSaveAsdialoButton.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                    fShowSaveAsdialoButton.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Show Save As dialog box");
                }

                return fShowSaveAsdialoButton;
            }
        }

        /// <summary>
        /// Gets Reference to ShowSaveAsdialoCheckBox
        /// </summary>
        public CheckBox ShowSaveAsdialoCheckBox
        {
            get
            {
                if (null == fShowSaveAsdialoCheckBox)
                {
                    fShowSaveAsdialoCheckBox = new CheckBox("ShowSaveAsdialoCheckBox", A32770Dup1Pane);
                    fShowSaveAsdialoCheckBox.UIMap.Scope = UIASeachScope.Children;
                    fShowSaveAsdialoCheckBox.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Show Save As dialog box");
                    fShowSaveAsdialoCheckBox.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1161");
                    fShowSaveAsdialoCheckBox.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                }

                return fShowSaveAsdialoCheckBox;
            }
        }

        /// <summary>
        /// Gets Reference to OpenthefileButtButton
        /// </summary>
        public Button OpenthefileButtButton
        {
            get
            {
                if (null == fOpenthefileButtButton)
                {
                    fOpenthefileButtButton = new Button("OpenthefileButtButton", A32770Dup1Pane);
                    fOpenthefileButtButton.UIMap.Scope = UIASeachScope.Children;
                    fOpenthefileButtButton.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1157");
                    fOpenthefileButtButton.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                    fOpenthefileButtButton.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Open the file");
                }

                return fOpenthefileButtButton;
            }
        }

        /// <summary>
        /// Gets Reference to LaunchWindowsExButton
        /// </summary>
        public Button LaunchWindowsExButton
        {
            get
            {
                if (null == fLaunchWindowsExButton)
                {
                    fLaunchWindowsExButton = new Button("LaunchWindowsExButton", A32770Dup1Pane);
                    fLaunchWindowsExButton.UIMap.Scope = UIASeachScope.Children;
                    fLaunchWindowsExButton.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1158");
                    fLaunchWindowsExButton.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                    fLaunchWindowsExButton.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Launch Windows Explorer");
                }

                return fLaunchWindowsExButton;
            }
        }

        /// <summary>
        /// Gets Reference to DoNothingButtonButton
        /// </summary>
        public Button DoNothingButtonButton
        {
            get
            {
                if (null == fDoNothingButtonButton)
                {
                    fDoNothingButtonButton = new Button("DoNothingButtonButton", A32770Dup1Pane);
                    fDoNothingButtonButton.UIMap.Scope = UIASeachScope.Children;
                    fDoNothingButtonButton.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1159");
                    fDoNothingButtonButton.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                    fDoNothingButtonButton.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Do Nothing");
                }

                return fDoNothingButtonButton;
            }
        }

        /// <summary>
        /// Gets Reference to DoNothingButtonRadioButton
        /// </summary>
        public RadioButton DoNothingButtonRadioButton
        {
            get
            {
                if (null == fDoNothingButtonRadioButton)
                {
                    fDoNothingButtonRadioButton = new RadioButton("DoNothingButtonRadioButton", A32770Dup1Pane);
                    fDoNothingButtonRadioButton.UIMap.Scope = UIASeachScope.Children;
                    fDoNothingButtonRadioButton.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Do Nothing");
                    fDoNothingButtonRadioButton.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1159");
                    fDoNothingButtonRadioButton.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                }

                return fDoNothingButtonRadioButton;
            }
        }

        /// <summary>
        /// Gets Reference to AftersavingthefText
        /// </summary>
        public Text AftersavingthefText
        {
            get
            {
                if (null == fAftersavingthefText)
                {
                    fAftersavingthefText = new Text("AftersavingthefText", A32770Dup1Pane);
                    fAftersavingthefText.UIMap.Scope = UIASeachScope.Children;
                    fAftersavingthefText.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Static");
                    fAftersavingthefText.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"After saving the file(s)");
                }

                return fAftersavingthefText;
            }
        }

        /// <summary>
        /// Gets Reference to A32770Dup2I1XPane
        /// </summary>
        public Pane A32770Dup2I1XPane
        {
            get
            {
                if (null == fA32770Dup2I1XPane)
                {
                    fA32770Dup2I1XPane = new Pane("A32770Dup2I1XPane", HPScanHPLaserJeWindow);
                    fA32770Dup2I1XPane.UIMap.Scope = UIASeachScope.Children;
                    fA32770Dup2I1XPane.UIMap.Index = 1;
                    fA32770Dup2I1XPane.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"#32770");
                }

                return fA32770Dup2I1XPane;
            }
        }

        /// <summary>
        /// Gets Reference to Button2132Button
        /// </summary>
        public Button Button2132Button
        {
            get
            {
                if (null == fButton2132Button)
                {
                    fButton2132Button = new Button("Button2132Button", HPScanHPLaserJeWindow);
                    fButton2132Button.UIMap.Scope = UIASeachScope.Children;
                    fButton2132Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"2132");
                    fButton2132Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                }

                return fButton2132Button;
            }
        }

        /// <summary>
        /// Gets Reference to Button1165Button
        /// </summary>
        public Button Button1165Button
        {
            get
            {
                if (null == fButton1165Button)
                {
                    fButton1165Button = new Button("Button1165Button", HPScanHPLaserJeWindow);
                    fButton1165Button.UIMap.Scope = UIASeachScope.Children;
                    fButton1165Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1165");
                    fButton1165Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                }

                return fButton1165Button;
            }
        }

        /// <summary>
        /// Gets Reference to Button288Button
        /// </summary>
        public Button Button288Button
        {
            get
            {
                if (null == fButton288Button)
                {
                    fButton288Button = new Button("Button288Button", HPScanHPLaserJeWindow);
                    fButton288Button.UIMap.Scope = UIASeachScope.Children;
                    fButton288Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"288");
                    fButton288Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                }

                return fButton288Button;
            }
        }

        /// <summary>
        /// Gets Reference to ScanEdit1869Edit
        /// </summary>
        public Edit ScanEdit1869Edit
        {
            get
            {
                if (null == fScanEdit1869Edit)
                {
                    fScanEdit1869Edit = new Edit("ScanEdit1869Edit", A32770Dup1Pane);
                    fScanEdit1869Edit.UIMap.Scope = UIASeachScope.Children;
                    fScanEdit1869Edit.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Edit");
                    fScanEdit1869Edit.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1869");                    
                }

                return fScanEdit1869Edit;
            }
        }

        /// <summary>
        /// Gets Reference to OKButton1Button
        /// </summary>
        public Button OKButton1Button
        {
            get
            {
                if (null == fOKButton1Button)
                {
                    fOKButton1Button = new Button("OKButton1Button", A32770Dup1Pane);
                    fOKButton1Button.UIMap.Scope = UIASeachScope.Children;
                    fOKButton1Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                    fOKButton1Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1");
                    fOKButton1Button.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"OK");
                }

                return fOKButton1Button;
            }
        }

        /// <summary>
        /// Gets Reference to YesButton1Button
        /// </summary>
        public Button YesButton1ButtonReplace
        {
            get
            {
                if (null == fYesButton1ButtonReplace)
                {
                    fYesButton1ButtonReplace = new Button("YesButton1ButtonReplace", HPScanHPLaserJePane);
                    fYesButton1ButtonReplace.UIMap.Scope = UIASeachScope.Children;
                    fYesButton1ButtonReplace.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Yes");
                    fYesButton1ButtonReplace.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1");
                    fYesButton1ButtonReplace.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                }

                return fYesButton1ButtonReplace;
            }
        }

        /// <summary>
        /// Gets Reference to NoButton1845Button
        /// </summary>
        public Button NoButton1845Button
        {
            get
            {
                if (null == fNoButton1845Button)
                {
                    fNoButton1845Button = new Button("NoButton1845Button", A32770Dup0I0XPane);
                    fNoButton1845Button.UIMap.Scope = UIASeachScope.Children;
                    fNoButton1845Button.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1845");
                    fNoButton1845Button.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                    fNoButton1845Button.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"No");
                }

                return fNoButton1845Button;
            }
        }

        /// <summary>
        /// Gets Reference to SavealocalcopyBButton
        /// </summary>
        public Button SavealocalcopyBButton
        {
            get
            {
                if (null == fSavealocalcopyBButton)
                {
                    fSavealocalcopyBButton = new Button("SavealocalcopyBButton", A32770Dup1Pane);
                    fSavealocalcopyBButton.UIMap.Scope = UIASeachScope.Children;
                    fSavealocalcopyBButton.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1160");
                    fSavealocalcopyBButton.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Save a local copy");
                    fSavealocalcopyBButton.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                }

                return fSavealocalcopyBButton;
            }
        }       

        /// <summary>
        /// Gets Reference to SavealocalcopyBCheckBox
        /// </summary>
        public CheckBox SavealocalcopyBCheckBox
        {
            get
            {
                if (null == fSavealocalcopyBCheckBox)
                {
                    fSavealocalcopyBCheckBox = new CheckBox("SavealocalcopyBCheckBox", A32770Dup1Pane);
                    fSavealocalcopyBCheckBox.UIMap.Scope = UIASeachScope.Children;
                    fSavealocalcopyBCheckBox.UIMap.SearchProperties.Add(UIASearchProperty.Name, @"Save a local copy");
                    fSavealocalcopyBCheckBox.UIMap.SearchProperties.Add(UIASearchProperty.AutomationId, @"1160");
                    fSavealocalcopyBCheckBox.UIMap.SearchProperties.Add(UIASearchProperty.ClassName, @"Button");
                }

                return fSavealocalcopyBCheckBox;
            }
        }
    }
}